# MACHINE LEARING IS MAKING THE COMPUTER TO LEARN FROM STUDYING DATA AND STATISTICS .

# MACHINE LEARING IS A PROGRAM THAT ANALYSIS DATA AND LEARN TO PREDICT THE OUTCOME .

# EXAMPLE OF DATA SET : list_data = [72,64,92,80,68,84,96,76,60,88] .

# THERE ARE 3 MAIN DATA TYPES USED IN MACHINE LEARNING THEY ARE NUMERICAL DATA , CATEGORICAL DATA AND ORDINAL DATA .

# NUMERICAL DATA IS DIVIDED INTO 2 TYPES : DISCRETE DATA AND CONTINUOUS DATA .

# DISCRETE DATA : NUMBERS THAT ARE LIMITED TO INTEGER LIKE NUMBER OF CARS PASSING BY A ROAD .

# CONTINUOUS DATA : NUMBERS THAT ARE OF INFINITE VALUE LIKE PRICE OF AN ITEM .

# CATEGORICAL DATA : VALUES THAT CANNOT BE COUNTED OR MEASURED LIKE COLOURS .

# ORDINAL DATA : THESE ARE LIKE CATEGORICAL DATA BUT CAN BE MEASURABLE OR COUNTABLE LIKE SCHOOL GRADES WHERE "A" IS BETTER THAN "B" .
